### ISSUE TITLE
Square ratio

### ISSUE THREAD

**Issue by jeremyjamez** [duanhong169/Camera#3]
Does it support a square ratio (1:1)? I tried it but it looks more like 4:3, it's not as square as expected.

**Comment by duanhong169** [comment]
It depends on the camera device, please check the supported aspect ratios by:
```java
photographer.getSupportedAspectRatios()
```

**Comment by duanhong169** [comment]
Long time no response, closed.

**Comment by AshutoshXus** [comment]
When i set ratio to1:1 and flip camera to back then it gets stuck
