### ISSUE TITLE
Pause video record

### ISSUE THREAD

**Issue by Vibinreji** [duanhong169/Camera#4]
Is there any option available to pause the video record and restart it?

**Comment by duanhong169** [comment]
Yes, but only support these actions when API level >= 24 (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N): 

https://github.com/duanhong169/Camera/blob/6077681d059eb5f8f01ffbf373ebc35ed01e3def/camera/src/main/java/top/defaults/camera/Photographer.java#L60-L68
