### ISSUE TITLE
cant integrate into existing project

### ISSUE THREAD

**Issue by suarezu** [duanhong169/Camera#6]
when
`implementation 'com.github.duanhong169:camera:1.0.3'`
is added to app/build.gradle, sync reports this error:

duplicate value for resource 'attr/mode' with config ''.

**Comment by duanhong169** [comment]
Seems that you used another library which contains a class named `CameraView` too?
Can you provide some information about that library?

**Comment by suarezu** [comment]
Genius! yes, that's the problem. I am testing quite a lot camera libraries, so some other library caused the chaos.

**Comment by duanhong169** [comment]
Greate, closed for now.
