### ISSUE TITLE
About ImageSize save problem

### ISSUE THREAD

**Issue by mskocabay** [duanhong169/Camera#8]
I am using huawei for devoloping. when i was image mode imageSize return 4608*3456 from Camere2Photographer.java . and seems toast message your image saved . But not saved in files folder. When i choose imageSize from dialog smaller size , saved. 

I tried in samsung phone no problem. All supported images saved. It is problem about Huawai phones ? How can i solve this problem.

Thank you.

**Comment by duanhong169** [comment]
Sorry, it's hard for me to solve this problem because of the specified device, please do some debugging with the source code if possible.

**Comment by mskocabay** [comment]
ok thank you.

**Comment by mskocabay** [comment]
in debug mode returns this message 
I/art: Compiler allocated 6MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int) or 7MB . And dont save the image to storage folder
